# Generated by Django 3.0.3 on 2020-02-19 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200219_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Vendor'),
        ),
    ]
