# Generated by Django 3.0.3 on 2020-02-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200219_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_stock',
            new_name='num_stocks',
        ),
    ]
